# serverless.yml

service: my-service

provider:
  name: aws
  runtime: nodejs18.x

functions:
  getUsersProgress:
    handler: src/getUsersProgress.getUsersProgress
    events:
      - http:
          path: progress
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                courseId: false

plugins:
  - serverless-offline
